services:

  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    # temporary to keep container running
    command: tail -f Cargo.toml
#    command: /bin/bash -c "cargo run -- --host=0.0.0.0"
    working_dir: /home/www/app/dev-server
    volumes:
      - ./:/home/www/app
    environment:
      VITE_HOST: node
      VITE_PORT: 5173
    ports:
      - "3000:3000"

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    command: /bin/bash -c "npm i && ./node_modules/.bin/vite --host=0.0.0.0"
    user: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
      IS_DOCKER: 1
    volumes:
      - ./:/home/node/app

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./public:/var/www/public
    environment:
      APP_HOST: app
      APP_PORT: 3000

#  db:
#    image: mysql
#    restart: always
#    environment:
#      MYSQL_DATABASE: rusty
#      MYSQL_ROOT_PASSWORD: my_secret_password
#    hostname: db
#    container_name: db
#    domainname: db
#    # (this is just an example, not intended to be a production configuration)
