server {
    listen       80;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /var/www/public;
        try_files $uri $uri/;
        gzip_static on;
    }

    location ~ .* {
        proxy_pass http://192.168.0.157:3000$uri;
    }
}
